// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbgyzisstcvrikdhpiil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiZ3l6aXNzdGN2cmlrZGhwaWlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDE5MzYsImV4cCI6MjA2OTk3NzkzNn0.7BsSmbkHDCKjZ516gTZmJnCYSH0bxLHNvL5_ty4J4S0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});